### ISSUE TITLE
Clase Polynomial.py smell

### ISSUE THREAD

**Issue by trm187** [PRIS2/Psi#1]
En el archivo Polynomial.py tienes dos clases, creo que el código estaría más limpio si separas las clases en dos archivos diferentes.

**Comment by luxor-g** [comment]
Lo pensé pero no es que la clase Monomial sea muy compleja y me gusta tenerlas en el mismo archivo por lo intimamente relacionadas que están y siempre se van a utilizar juntas.

Quizás lo que sí habría que hacer es ponerle un nombre mejor al archivo pero no se me ocurre ninguno.
