### ISSUE TITLE
Pocos comentarios

### ISSUE THREAD

**Issue by trm187** [PRIS2/Psi#2]
Creo que, aunque el código es muy legible, sería mejor añadir algunos comentarios explicativos. Sobretodo en métodos más complicados como son fill_gaps, simplify o __add__.

**Comment by luxor-g** [comment]
Simplify y add al ser operaciones básicas de los polinomios no creo que necesiten explicación pero explicar un poco el método fill_gaps si puede ayudar a alguien.
